[package]
name = "esm-bindings"
version = "0.2.0"
authors = ["tRuTrIx <trutrix@monocyte.host>", "StealthOfKing <sok@monocyte.host>"]
edition = "2021"
description = "ESM struct bindings"

[dependencies]

[build-dependencies]
bindgen = "0.70"
